"""Add User model

Revision ID: dfe8f88e4f67
Revises: e08b90822536
Create Date: 2025-11-17 15:12:48.982665

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'dfe8f88e4f67'
down_revision = 'e08b90822536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TenantProfiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('preferences', postgresql.JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('RecommendationLogs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('SavedSearches', 'user_id')
    op.add_column('SavedSearches', sa.Column('user_id', sa.UUID(), nullable=True)) # nullable=True as per original table
    op.create_foreign_key(None, 'SavedSearches', 'users', ['user_id'], ['id'])
    op.drop_index('idx_payments_chapa_tx_ref', table_name='payments')
    op.drop_index('idx_payments_property_id', table_name='payments')
    op.drop_index('idx_payments_status', table_name='payments')
    op.drop_index('idx_payments_user_id', table_name='payments')
    
    op.create_foreign_key(None, 'payments', 'users', ['user_id'], ['id'])
    op.alter_column('properties', 'amenities',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(),
               existing_nullable=True,
               postgresql_using='amenities::jsonb')
    op.alter_column('properties', 'photos',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(),
               existing_nullable=True,
               postgresql_using='photos::jsonb')
    op.drop_index('fts_idx', table_name='properties')
    op.drop_index('idx_properties_lat_lon', table_name='properties')
    op.drop_index('idx_properties_location', table_name='properties')
    op.drop_index('idx_properties_price', table_name='properties')
    op.drop_index('idx_properties_status', table_name='properties')
    op.drop_index('idx_properties_user_id', table_name='properties')
    op.drop_constraint('properties_payment_id_key', 'properties', type_='unique')
    op.drop_column('properties', 'fts')
    op.create_foreign_key(None, 'properties', 'payments', ['payment_id'], ['id'])
    op.create_foreign_key(None, 'properties', 'users', ['user_id'], ['id'])
    op.drop_index('idx_refresh_token_expires_at', table_name='refresh_tokens')
    op.drop_index('idx_refresh_token_user_id', table_name='refresh_tokens')
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               type_=postgresql.BYTEA(),
               existing_nullable=False,
               postgresql_using='phone_number::bytea')
    op.alter_column('users', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using='created_at::timestamptz')
    op.alter_column('users', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using='updated_at::timestamptz')
    op.drop_index('ix_users_email', table_name='users')
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               postgresql_using='updated_at::timestamp')
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               postgresql_using='created_at::timestamp')
    op.alter_column('users', 'phone_number',
               existing_type=sa.BYTEA(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               postgresql_using='phone_number::varchar(20)')
    op.create_index('idx_refresh_token_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_index('idx_refresh_token_expires_at', 'refresh_tokens', ['expires_at'], unique=False)
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.add_column('properties', sa.Column('fts', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('properties_payment_id_key', 'properties', ['payment_id'])
    op.create_index('idx_properties_user_id', 'properties', ['user_id'], unique=False)
    op.create_index('idx_properties_status', 'properties', ['status'], unique=False)
    op.create_index('idx_properties_price', 'properties', ['price'], unique=False)
    op.create_index('idx_properties_location', 'properties', ['location'], unique=False)
    op.create_index('idx_properties_lat_lon', 'properties', ['lat', 'lon'], unique=False)
    op.create_index('fts_idx', 'properties', ['fts'], unique=False, postgresql_using='gin')
    op.alter_column('properties', 'photos',
               existing_type=postgresql.JSONB(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='photos::json')
    op.alter_column('properties', 'amenities',
               existing_type=postgresql.JSONB(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='amenities::json')
    op.drop_constraint(None, 'payments', type_='foreignkey') # This is the first one (for user_id)
    # op.drop_constraint(None, 'payments', type_='foreignkey') # This is the second one (for property_id) - REMOVED
    op.create_index('idx_payments_user_id', 'payments', ['user_id'], unique=False)
    op.create_index('idx_payments_status', 'payments', ['status'], unique=False)
    op.create_index('idx_payments_property_id', 'payments', ['property_id'], unique=False)
    op.create_index('idx_payments_chapa_tx_ref', 'payments', ['chapa_tx_ref'], unique=False)
    op.drop_constraint(None, 'SavedSearches', type_='foreignkey') # Drop FK first
    op.drop_column('SavedSearches', 'user_id')
    op.add_column('SavedSearches', sa.Column('user_id', sa.INTEGER(), nullable=True)) # nullable=True as per original table
    op.drop_table('RecommendationLogs')
    op.drop_table('TenantProfiles')
    # ### end Alembic commands ###