"""Initial clean migration

Revision ID: fae2c32ac672
Revises: 
Create Date: 2025-11-17 23:13:22.398095

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fae2c32ac672'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create tables
    op.create_table('TenantPreferences',
    sa.Column('id', sa.Integer(), sa.Identity(), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('job_school_location', sa.String(length=255), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('house_type', sa.String(length=50), nullable=True),
    sa.Column('family_size', sa.Integer(), nullable=True),
    sa.Column('preferred_amenities', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.text('now()')),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('RecommendationLogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_preference_id', sa.Integer(), nullable=False),
    sa.Column('recommendation', postgresql.JSONB(), nullable=True),
    sa.Column('feedback', postgresql.JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.text('now()')),
    sa.PrimaryKeyConstraint('id')
    )

    # Add Foreign Keys
    op.create_foreign_key('fk_tenantpreferences_user_id', 'TenantPreferences', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_recommendationlogs_tenant_preference_id', 'RecommendationLogs', 'TenantPreferences', ['tenant_preference_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop Foreign Keys
    op.drop_constraint('fk_recommendationlogs_tenant_preference_id', 'RecommendationLogs', type_='foreignkey')
    op.drop_constraint('fk_tenantpreferences_user_id', 'TenantPreferences', type_='foreignkey')

    # Drop tables
    op.drop_table('RecommendationLogs')
    op.drop_table('TenantPreferences')
    # ### end Alembic commands ###
    
